### ISSUE TITLE
Redirect is depricated

### ISSUE THREAD

**Issue by Abhishekkumar4444** [myogeshchavan97/hackernews-clone-react-app#1]
Redirect is not working .Please make changes

**Comment by myogeshchavan97** [comment]
Hi @Abhishekkumar4444 , Looks like you're using react-router-dom version 6 which is the latest version which has breaking change and Redirect is removed in this version.

If you want to run this application, you need to use react-router-dom version 5. So install it using 

`npm install react-router-dom@5.3.0` or `yarn add react-router-dom@5.3.0`
